# Generated by Django 3.2.3 on 2021-05-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='guid',
            field=models.CharField(default='2ee1e1299c364fb59ba0323be456d7c4', max_length=40),
        ),
    ]
