# Generated by Django 3.2.3 on 2021-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='guid',
            field=models.CharField(default='e62e88bc9e534e5a8a8ebfba9a7dbd84', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='primary_subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='secondary_subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
