# Generated by Django 3.2.4 on 2021-06-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0002_alter_teacher_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='guid',
            field=models.CharField(default='9bf85abcb8c0492da288050407dd57b8', max_length=40),
        ),
    ]
