# Generated by Django 3.2.4 on 2021-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0003_alter_teacher_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='guid',
            field=models.CharField(default='8475ee37b87d4a1fb7cbdc8e2f3a9c04', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
